---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm
data:
  bootstrap.json: |
    This is bootstrap.json
---
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  file1: |
    dGVzdDEK
  file2: |
    dGVzdDIK
---
apiVersion: v1
kind: Pod
metadata:
  name: godev
  labels:
    name: godev
spec:
  containers:
  - name: golang
    image: deis/go-dev
    command:
      - "sleep"
      - "1000000000"
    resources:
      limits:
        memory: "256Mi"
        cpu: 1
    env:
      - name: GRPC_XDS_BOOTSTRAP
        value: /bootstrap.json
      - name: GRPC_GO_LOG_VERBOSITY_LEVEL
        value: "99"
      - name: GRPC_GO_LOG_SEVERITY_LEVEL
        value: info
    volumeMounts:
      - name: config-volume
        mountPath: /xds-config
        readOnly: false
      - name: secrets-volume
        mountPath: /secrets
  volumes:
    - name: config-volume
      configMap:
        name: test-cm
    - name: secrets-volume
      secret:
        secretName: test-secret
